myID=hud.towers_built
myType="Quad Gun"
level=1
reload_counter=0
reload_time=store.quadgun_reload_time
attack_damage=store.quadgun_attack_damage
attack_range=store.quadgun_attack_range+(10*store.perk_lvl_scope)
knockback=store.quadgun_knockback
ability=store.quadgun_ability
critical_chance=store.quadgun_critical_chance+(store.perk_lvl_sharpshooter)
cost=10
image_speed=0
